export default {
    addonName: "org",
    title: "ORBIS - Global Organization Network",
    logLabel: "Org UI",
    outputDir: "_site",
    jsBundles: [
        {
            name: "Org UI app",
            output: "org-ui.js",
            sources: [
                "src/runtime.js",
                "src/registry/store.js",
                "src/bridge.js",
                "src/portal/data.js",
                "src/portal/store.js",
                "src/portal/getters.js",
                "src/portal/actions.js",
                "src/components/navbar.js",
                "src/components/header.js",
                "src/components/hero.js",
                "src/components/footer.js",
                "src/components/modal.js",
                "src/components/panelCard.js",
                "src/components/portal/metricCard.js",
                "src/components/portal/simpleStat.js",
                "src/components/portal/overviewCard.js",
                "src/components/portal/fleetCard.js",
                "src/components/portal/treasuryCard.js",
                "src/components/portal/assetsCard.js",
                "src/components/portal/membersCard.js",
                "src/components/portal/activityCard.js",
                "src/components/portal/futureCard.js",
                "src/components/portal/dangerCard.js",
                "src/components/portal/modalLayer.js",
                "src/views/DisbandedView.js",
                "src/views/PortalView.js",
                "src/views/RegistrationView.js",
                "src/views/HomeView.js",
                "src/components/AppShell.js",
                "src/bootstrap.js",
            ],
        },
    ],
    cssBundles: [
        {
            name: "Org UI styles",
            output: "org-ui.css",
            sources: ["src/styles.css"],
        },
    ],
    site: {
        styles: ["org-ui.css"],
        commonScripts: ["forge-webui.js"],
        scripts: ["org-ui.js"],
    },
};
